-- A teacher has at most one Class Analysis class.
-- Older databases may not have the legacy ClassAccess table; the schema-level
-- unique constraint below is represented in the current database separately.
