import type { FormEvent } from "react";
import type { GetServerSideProps } from "next";
import Link from "next/link";
import { getServerSession } from "next-auth/next";
import { signOut } from "next-auth/react";
import { useRouter } from "next/router";
import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowRight, Bell, BookOpen, GraduationCap, LayoutDashboard, Link2, LogOut, Plus, Search, Settings, Users, X } from "lucide-react";
import { authOptions } from "../../../lib/authOptions";
import { prisma } from "../../../lib/prisma";

type Teacher = { id: string; name: string; email: string; assignments: { subject: string; className: string }[]; classes: string[]; proctorOf: string[]; createdAt: string };
type Props = { teachers: Teacher[] };
const nav = [["/admin", "Dashboard", LayoutDashboard], ["/admin/classes", "Classes", BookOpen], ["/admin/students", "Students", Users], ["/admin/teachers", "Teachers", GraduationCap], ["/admin/subjects", "Subjects", BookOpen], ["/admin/assignments", "Assignments", Link2], ["/admin/settings", "System Settings", Settings]] as const;

export default function TeachersPage({ teachers }: Props) {
  const router = useRouter(); const [query, setQuery] = useState(""); const [modal, setModal] = useState<"add" | "edit" | null>(null); const [selected, setSelected] = useState<Teacher | null>(null); const [form, setForm] = useState({ name: "", email: "" }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (router.query.add === "1") { setModal("add"); router.replace("/admin/teachers", undefined, { shallow: true }); } }, [router]);
  const filtered = useMemo(() => { const q = query.toLowerCase().trim(); return teachers.filter(t => !q || `${t.name} ${t.email} ${t.assignments.map(a => `${a.subject} ${a.className}`).join(" ")}`.toLowerCase().includes(q)); }, [teachers, query]);
  const openAdd = () => { setError(""); setSelected(null); setForm({ name: "", email: "" }); setModal("add"); };
  const openEdit = (teacher: Teacher) => { setError(""); setSelected(teacher); setForm({ name: teacher.name, email: teacher.email }); setModal("edit"); };
  const save = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(""); try { const response = await fetch("/api/admin/teachers", { method: modal === "edit" ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, id: selected?.id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to save teacher"); window.location.reload(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to save teacher"); setBusy(false); } };
  return <div className="admin-section-page"><aside className="admin-sidebar"><Link href="/admin" className="admin-brand"><span className="admin-brand-mark"><Activity size={22}/></span><span>ClassPulse</span></Link><p className="admin-portal-label">ADMIN PORTAL</p><nav className="admin-nav">{nav.map(([href, label, Icon]) => <Link key={label} href={href} className={`admin-nav-link ${label === "Teachers" ? "active" : ""}`}><Icon size={19}/>{label}</Link>)}</nav><div className="admin-user-block"><div className="admin-user"><span className="admin-avatar">A</span><span><strong>Admin</strong><small>Administrator</small></span></div><button className="admin-signout" onClick={() => signOut({ callbackUrl: "/login" })}><LogOut size={17}/> Sign out</button></div></aside>
  <main className="admin-main"><header className="admin-header"><div><h1>Teachers</h1><p>Manage teachers, their class access, subjects, and proctor responsibilities.</p></div><div className="admin-header-actions"><label className="admin-search"><Search size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search teachers, subjects..."/></label><button className="admin-icon-button" aria-label="Notifications"><Bell size={20}/></button><button className="section-primary" onClick={openAdd}><Plus size={16}/> Add Teacher</button></div></header>
  <section className="section-summary"><div className="summary-card teacher-tone"><span className="summary-icon"><GraduationCap size={21}/></span><div><strong>{teachers.length}</strong><small>Total Teachers</small></div></div><div className="summary-card blue-tone"><span className="summary-icon"><BookOpen size={21}/></span><div><strong>{new Set(teachers.flatMap(t => t.assignments.map(a => a.subject))).size}</strong><small>Subjects Taught</small></div></div><div className="summary-card green-tone"><span className="summary-icon"><Users size={21}/></span><div><strong>{new Set(teachers.flatMap(t => t.classes)).size}</strong><small>Classes Covered</small></div></div><div className="summary-card gold-tone"><span className="summary-icon"><Link2 size={21}/></span><div><strong>{teachers.reduce((n, t) => n + t.assignments.length, 0)}</strong><small>Active Assignments</small></div></div></section>
  <section className="section-panel"><div className="section-panel-head"><div><h2>All Teachers <span>{filtered.length}</span></h2><p>Teacher records are stored in the institution database.</p></div><label className="section-search"><Search size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by name or email"/></label></div><div className="section-table-wrap"><table className="section-table"><thead><tr><th>Teacher</th><th>Subjects</th><th>Classes</th><th>Proctor</th><th>Joined</th><th></th></tr></thead><tbody>{filtered.map(t => <tr key={t.id}><td><div className="person-cell"><span className="person-avatar">{t.name.charAt(0).toUpperCase()}</span><div><strong>{t.name}</strong><small>{t.email}</small></div></div></td><td>{t.assignments.length ? <div className="tag-list">{t.assignments.slice(0, 2).map(a => <span key={`${a.className}-${a.subject}`}>{a.subject}</span>)}{t.assignments.length > 2 && <em>+{t.assignments.length - 2}</em>}</div> : <span className="muted">No assignment</span>}</td><td>{t.classes.length || 0}</td><td>{t.proctorOf.length ? <span className="status-chip green"><i/> {t.proctorOf.length} class{t.proctorOf.length > 1 ? "es" : ""}</span> : <span className="muted">Not assigned</span>}</td><td>{new Date(t.createdAt).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</td><td><button className="row-action" onClick={() => openEdit(t)}>Edit <ArrowRight size={14}/></button></td></tr>)}{!filtered.length && <tr><td colSpan={6} className="section-empty">No teachers match your search.</td></tr>}</tbody></table></div></section></main>
  {modal && <div className="modal-backdrop" onMouseDown={() => !busy && setModal(null)}><div className="admin-modal" onMouseDown={e => e.stopPropagation()}><div className="modal-head"><div><span>TEACHER MANAGEMENT</span><h2>{modal === "edit" ? "Edit Teacher" : "Add Teacher"}</h2></div><button onClick={() => setModal(null)} disabled={busy}><X size={19}/></button></div><form onSubmit={save}><label>Full name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="e.g. Dr. Neha Sharma"/></label><label>Email address<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="teacher@college.edu"/></label>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" onClick={() => setModal(null)}>Cancel</button><button className="section-primary" disabled={busy}>{busy ? "Saving..." : modal === "edit" ? "Save Changes" : "Add Teacher"}</button></div></form></div></div>}
  </div>;
}
export const getServerSideProps: GetServerSideProps<Props> = async ctx => { const session = await getServerSession(ctx.req, ctx.res, authOptions); if (!session?.user) return { redirect: { destination: "/login", permanent: false } }; if ((session.user as any).role !== "ADMIN") return { redirect: { destination: "/dashboard", permanent: false } }; const rows = await prisma.user.findMany({ where: { role: "TEACHER" }, orderBy: { name: "asc" }, include: { assignments: { include: { subject: { include: { section: { include: { class: true } } } } } }, classAccess: { include: { class: true } }, proctorOf: { select: { id: true } } } }); const teachers = rows.map(t => ({ id: t.id, name: t.name, email: t.email, assignments: t.assignments.map(a => ({ subject: a.subject.name, className: a.subject.section.class.program })), classes: Array.from(new Set([...t.classAccess.map(a => a.class.program), ...t.assignments.map(a => a.subject.section.class.program)])), proctorOf: t.proctorOf.map(p => p.id), createdAt: t.createdAt.toISOString() })); return { props: { teachers } }; };
