import type { GetServerSideProps } from "next";
import Link from "next/link";
import { useMemo, useState } from "react";
import { getServerSession } from "next-auth/next";
import { signOut } from "next-auth/react";
import { ArrowRight, Bell, BookOpen, Building2, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, GraduationCap, LayoutDashboard, Link2, LogOut, Pencil, Search, Settings, Users } from "lucide-react";
import { authOptions } from "../../lib/authOptions";
import { prisma } from "../../lib/prisma";

interface ClassItem { id:string; name:string; department:string; semester:number; program:string; academicYear:string; students:number; teachers:number; subjects:number; sections:number; updated:string }
interface Props { classes:ClassItem[]; departmentCount:number; semesterCount:number; totalStudents:number }
const fmt=(v:string)=>new Date(v).toLocaleString("en-IN",{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"});

export default function ClassesPage({classes,departmentCount,semesterCount,totalStudents}:Props){
 const [q,setQ]=useState(""); const [dept,setDept]=useState("All Departments"); const [sem,setSem]=useState("All Semesters"); const [selectedId,setSelectedId]=useState(classes[0]?.id||""); const [page,setPage]=useState(1); const size=10;
 const depts=useMemo(()=>Array.from(new Set(classes.map(x=>x.department))).sort(),[classes]); const sems=useMemo(()=>Array.from(new Set(classes.map(x=>x.semester))).sort((a,b)=>a-b),[classes]);
 const filtered=useMemo(()=>classes.filter(x=>{const n=q.toLowerCase().trim();return(!n||[x.name,x.department,x.program,x.academicYear].some(v=>v.toLowerCase().includes(n)))&&(dept==="All Departments"||x.department===dept)&&(sem==="All Semesters"||String(x.semester)===sem)}),[classes,q,dept,sem]);
 const pages=Math.max(1,Math.ceil(filtered.length/size)); const current=Math.min(page,pages); const visible=filtered.slice((current-1)*size,current*size); const selected=classes.find(x=>x.id===selectedId)||visible[0]||classes[0];
 return <div className="admin-classes-page"><aside className="admin-classes-sidebar"><Link href="/admin" className="admin-classes-brand"><span className="admin-classes-logo">∿</span><b>ClassPulse</b></Link><small className="admin-classes-portal">ADMIN PORTAL</small><nav>{[["/admin","Dashboard",LayoutDashboard],["/admin/classes","Classes",BookOpen],["/admin/students","Students",Users],["/admin/teachers","Teachers",GraduationCap],["/admin/subjects","Subjects",BookOpen],["/admin/assignments","Assignments",Link2],["/admin/settings","System Settings",Settings]].map(([href,label,Icon]:any)=><Link key={label} href={href} className={label==="Classes"?"active":""}><Icon size={18}/>{label}</Link>)}</nav><div className="admin-classes-user"><div><span>A</span><p><b>Admin</b><small>Administrator</small></p></div><button onClick={()=>signOut({callbackUrl:"/login"})}><LogOut size={17}/>Sign out</button></div></aside>
 <main className="admin-classes-main"><header className="admin-classes-header"><div><h1>Classes</h1><p>Manage all classes, view details, and organize class structure.</p></div><div className="admin-classes-header-actions"><label className="admin-classes-global-search"><Search size={18}/><input placeholder="Search classes, departments..." value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></label><button className="admin-classes-bell"><Bell size={20}/><i/></button><div className="admin-classes-date"><CalendarDays size={17}/><span>Mon, 9 Sept 2026<br/><b>11:23 PM</b></span></div><button className="admin-classes-create">+ Create Class</button></div></header>
 <section className="admin-classes-summary"><div className="blue"><span><Users/></span><strong>{classes.length}</strong><small>Total Classes</small></div><div className="green"><span><Building2/></span><strong>{departmentCount}</strong><small>Departments</small></div><div className="gold"><span><GraduationCap/></span><strong>{semesterCount}</strong><small>Semesters</small></div><div className="pink"><span><BookOpen/></span><strong>{totalStudents}</strong><small>Total Students</small></div></section>
 <section className="admin-classes-layout"><div className="admin-classes-table-card"><div className="admin-classes-table-head"><h2><BookOpen size={21}/>All Classes ({filtered.length})</h2><div className="admin-classes-filters"><label><select value={dept} onChange={e=>{setDept(e.target.value);setPage(1)}}><option>All Departments</option>{depts.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label><label><select value={sem} onChange={e=>{setSem(e.target.value);setPage(1)}}><option>All Semesters</option>{sems.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label><label className="admin-classes-inline-search"><Search size={15}/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Search classes..."/></label></div></div><div className="admin-classes-table-wrap"><table className="admin-classes-table"><thead><tr><th>Class</th><th>Department</th><th>Semester</th><th>Students</th><th>Teachers</th><th>Subjects</th><th>Last Updated</th><th>Actions</th></tr></thead><tbody>{visible.map(x=><tr key={x.id} className={selected?.id===x.id?"selected":""} onClick={()=>setSelectedId(x.id)}><td><b>{x.name}</b><small>{x.sections} section{x.sections===1?"":"s"}</small></td><td>{x.department}</td><td>{x.semester}</td><td>{x.students}</td><td>{x.teachers}</td><td>{x.subjects}</td><td>{fmt(x.updated)}</td><td><button onClick={e=>{e.stopPropagation();setSelectedId(x.id)}}>⋮</button></td></tr>)}{!visible.length&&<tr><td colSpan={8} className="admin-classes-empty">No classes match your filters.</td></tr>}</tbody></table></div><div className="admin-classes-pagination"><span>Showing {filtered.length?(current-1)*size+1:0}–{Math.min(current*size,filtered.length)} of {filtered.length} classes</span><div><button disabled={current===1} onClick={()=>setPage(current-1)}><ChevronLeft size={15}/></button>{Array.from({length:pages},(_,i)=>i+1).slice(0,4).map(n=><button key={n} className={n===current?"current":""} onClick={()=>setPage(n)}>{n}</button>)}<button disabled={current===pages} onClick={()=>setPage(current+1)}><ChevronRight size={15}/></button></div></div></div>
 {selected&&<aside className="admin-classes-detail"><div className="detail-head"><div><h2>{selected.name}</h2><p>Department of {selected.department}</p></div><button><Pencil size={14}/>Edit Class</button></div><div className="detail-tabs"><button className="active">Overview</button><button>Subjects ({selected.subjects})</button><button>Teachers ({selected.teachers})</button><button>Students ({selected.students})</button></div><div className="detail-list"><div><BookOpen/><span>Class Name</span><b>{selected.name}</b></div><div><Building2/><span>Department</span><b>{selected.department}</b></div><div><GraduationCap/><span>Semester</span><b>{selected.semester}</b></div><div><Users/><span>Total Students</span><b>{selected.students}</b></div><div><GraduationCap/><span>Total Teachers</span><b>{selected.teachers}</b></div><div><BookOpen/><span>Total Subjects</span><b>{selected.subjects}</b></div><div><CalendarDays/><span>Last Updated</span><b>{fmt(selected.updated)}</b></div></div><div className="detail-actions"><h3>Quick Actions</h3><div><Link href="/admin/students"><Users/>View Students<ArrowRight/></Link><Link href="/admin/subjects"><BookOpen/>Manage Subjects<ArrowRight/></Link><Link href="/admin/assignments"><GraduationCap/>Assign Teachers<ArrowRight/></Link><button><Pencil/>Edit Class<ArrowRight/></button></div></div></aside>}</section></main></div>
}
export const getServerSideProps:GetServerSideProps<Props>=async(ctx)=>{const session=await getServerSession(ctx.req,ctx.res,authOptions);if(!session?.user)return{redirect:{destination:"/login",permanent:false}};if((session.user as any).role!=="ADMIN")return{redirect:{destination:"/dashboard",permanent:false}};const [classes,depts]=await Promise.all([prisma.class.findMany({include:{department:true,sections:{include:{students:{select:{id:true}},subjects:{include:{assignments:{select:{teacherId:true}}}}}}},orderBy:[{department:{name:"asc"}},{semester:"desc"}]}),prisma.department.findMany({select:{id:true}})]);const items=classes.map(x=>{const teachers=new Set(x.sections.flatMap(s=>s.subjects.flatMap(sub=>sub.assignments.map(a=>a.teacherId))));return{id:x.id,name:`${x.department.name} ${x.semester}`,department:x.department.name,semester:x.semester,program:x.program,academicYear:x.academicYear,students:x.sections.reduce((n,s)=>n+s.students.length,0),teachers:teachers.size,subjects:x.sections.reduce((n,s)=>n+s.subjects.length,0),sections:x.sections.length,updated:x.createdAt.toISOString()}});return{props:{classes:items,departmentCount:depts.length,semesterCount:new Set(items.map(x=>x.semester)).size,totalStudents:items.reduce((n,x)=>n+x.students,0)}}};