import type { GetServerSideProps } from "next";
import Link from "next/link";
import { getServerSession } from "next-auth/next";
import { signOut } from "next-auth/react";
import { Activity, ArrowRight, Bell, BookOpen, GraduationCap, LayoutDashboard, Link2, LogOut, Menu, RefreshCw, Settings, ShieldCheck, UserPlus, Users } from "lucide-react";
import { authOptions } from "../../lib/authOptions";
import { prisma } from "../../lib/prisma";

interface ActivityRow { text:string; detail:string; date:string; type:string; timestamp:number }
interface Props { adminName:string; counts:{students:number;teachers:number;classes:number;subjects:number}; system:{database:boolean;sheetsLinked:number;lastSync:string|null}; activity:ActivityRow[] }
const formatDate=(value:Date|null)=>value?value.toLocaleString("en-IN",{day:"numeric",month:"short",hour:"numeric",minute:"2-digit"}):"Never";

export default function AdminDashboard({adminName,counts,system,activity}:Props){
 const firstName=adminName.split(" ")[0]||"Admin";
 const sheetStatus=system.sheetsLinked>0&&system.lastSync?"Connected":"Not configured";
 return <div className="admin-shell"><aside className="admin-sidebar"><Link href="/admin" className="admin-brand"><span className="admin-brand-mark"><Activity size={22}/></span><span>ClassPulse</span></Link><p className="admin-portal-label">ADMIN PORTAL</p><nav className="admin-nav"><Link href="/admin" className="admin-nav-link active"><LayoutDashboard size={19}/> Dashboard</Link><Link href="/admin/classes" className="admin-nav-link"><BookOpen size={19}/> Classes</Link><Link href="/admin/students" className="admin-nav-link"><Users size={19}/> Students</Link><Link href="/admin/teachers" className="admin-nav-link"><GraduationCap size={19}/> Teachers</Link><Link href="/admin/subjects" className="admin-nav-link"><BookOpen size={19}/> Subjects</Link><Link href="/admin/assignments" className="admin-nav-link"><Link2 size={19}/> Assignments</Link><Link href="/admin/settings" className="admin-nav-link"><Settings size={19}/> System Settings</Link></nav><div className="admin-user-block"><div className="admin-user"><span className="admin-avatar">A</span><span><strong>Admin</strong><small>Administrator</small></span></div><button className="admin-signout" onClick={()=>signOut({callbackUrl:"/login"})}><LogOut size={17}/> Sign out</button></div></aside>
 <main className="admin-main"><header className="admin-header"><div><div className="admin-mobile-brand"><span className="admin-brand-mark"><Activity size={18}/></span><strong>ClassPulse</strong></div><h1>Good evening, {firstName}</h1><p>Here&apos;s a quick overview of your institution and system.</p></div><div className="admin-header-actions"><label className="admin-search"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4.2 4.2"/></svg><input placeholder="Search for students, teachers, classes..."/></label><button className="admin-icon-button" aria-label="Notifications"><Bell size={20}/><span className="notification-dot"/></button><button className="admin-menu-button"><Menu size={20}/></button></div></header>
 <section className="admin-stats"><Link href="/admin/students" className="admin-stat-card student"><span className="admin-stat-icon"><Users size={23}/></span><span><strong>{counts.students}</strong><small>Students</small></span><ArrowRight size={17}/></Link><Link href="/admin/teachers" className="admin-stat-card teacher"><span className="admin-stat-icon"><GraduationCap size={23}/></span><span><strong>{counts.teachers}</strong><small>Teachers</small></span><ArrowRight size={17}/></Link><Link href="/admin/classes" className="admin-stat-card class"><span className="admin-stat-icon"><BookOpen size={23}/></span><span><strong>{counts.classes}</strong><small>Classes</small></span><ArrowRight size={17}/></Link><Link href="/admin/subjects" className="admin-stat-card subject"><span className="admin-stat-icon"><BookOpen size={23}/></span><span><strong>{counts.subjects}</strong><small>Unique Subjects</small></span><ArrowRight size={17}/></Link></section>
 <section className="admin-grid-top"><div className="admin-panel"><div className="admin-panel-heading"><h2><span className="heading-status-dot"/> System Status</h2><Link href="/admin/settings">Manage <ArrowRight size={14}/></Link></div><div className="status-list"><div className="status-row"><span className="status-label"><span className="status-symbol sheets">G</span> Google Sheets</span><span className="status-value"><i className={`status-dot ${sheetStatus==="Connected"?"good":"warn"}`}/>{sheetStatus}</span><small>Last sync<br/>{system.lastSync||"Never"}</small><span className="status-more">⋮</span></div><div className="status-row"><span className="status-label"><span className="status-symbol database">●</span> Database</span><span className="status-value"><i className={`status-dot ${system.database?"good":"bad"}`}/>{system.database?"Operational":"Unavailable"}</span><small>Last checked<br/>{system.database?formatDate(new Date()):"Unavailable"}</small><span className="status-more">⋮</span></div><div className="status-row"><span className="status-label"><span className="status-symbol shield"><ShieldCheck size={15}/></span> Authentication</span><span className="status-value"><i className={system.database?"status-dot good":"status-dot bad"}/>{system.database?"Operational":"Unavailable"}</span><small>{counts.students+counts.teachers} accounts</small><span className="status-more">⋮</span></div></div></div>
 <div className="admin-panel quick-panel"><div className="admin-panel-heading"><h2><span className="heading-lightning">ϟ</span> Quick Actions</h2><Link href="/admin">View All <ArrowRight size={14}/></Link></div><div className="quick-actions"><Link href="/admin/students/new" className="quick-action student-action"><span><UserPlus size={22}/></span><b>Add Student</b></Link><Link href="/admin/teachers/new" className="quick-action teacher-action"><span><UserPlus size={22}/></span><b>Add Teacher</b></Link><Link href="/admin/classes/new" className="quick-action class-action"><span><BookOpen size={22}/></span><b>Create Class</b></Link><Link href="/admin/subjects/new" className="quick-action subject-action"><span><BookOpen size={22}/></span><b>Add Subject</b></Link><Link href="/admin/assignments" className="quick-action assignment-action"><span><Link2 size={22}/></span><b>Manage Assignments</b></Link><Link href="/admin/settings" className="quick-action sync-action"><span><RefreshCw size={22}/></span><b>Sync Now</b></Link></div></div></section>
 <section className="admin-grid-bottom"><div className="admin-panel activity-panel"><div className="admin-panel-heading"><h2><Activity size={18}/> Recent Activity</h2><Link href="/admin">View All <ArrowRight size={14}/></Link></div><div className="activity-list">{activity.length?activity.map((item,index)=><div className="activity-row" key={`${item.text}-${item.timestamp}-${index}`}><span className={`activity-dot activity-${index%4}`}>{item.type==="student"?<Users size={15}/>:item.type==="teacher"?<GraduationCap size={15}/>:item.type==="subject"?<BookOpen size={15}/>:<Link2 size={15}/>}</span><div><strong>{item.text}</strong><small>{item.detail}</small></div><time>{item.date}</time></div>):<div className="empty-activity">No recent activity yet.</div>}</div></div></section>
 </main></div>;
}

export const getServerSideProps:GetServerSideProps<Props>=async(ctx)=>{const session=await getServerSession(ctx.req,ctx.res,authOptions);if(!session?.user)return{redirect:{destination:"/login",permanent:false}};if((session.user as any).role!=="ADMIN")return{redirect:{destination:"/dashboard",permanent:false}};
 try{
  const [students,teachers,classesCount,subjectRows,latestSync,studentsRecent,teachersRecent,subjectsRecent,assignmentsRecent,sheetLinks]=await Promise.all([
   prisma.student.count(),
   prisma.user.count({where:{role:"TEACHER"}}),
   prisma.class.count(),
   prisma.subject.findMany({select:{name:true}}),
   prisma.sheetLink.findFirst({orderBy:{lastSyncAt:"desc"},select:{lastSyncAt:true}}),
   prisma.student.findMany({take:4,orderBy:{createdAt:"desc"},include:{section:{include:{class:{include:{department:true}}}}}),
   prisma.user.findMany({where:{role:"TEACHER"},take:4,orderBy:{createdAt:"desc"}}),
   prisma.subject.findMany({take:4,orderBy:{createdAt:"desc"},include:{section:{include:{class:{include:{department:true}}}}}),
   prisma.assignment.findMany({take:4,orderBy:{createdAt:"desc"},include:{teacher:true,subject:true}}),
   prisma.sheetLink.count()
  ]);
  const uniqueSubjects=new Set(subjectRows.map(x=>x.name.trim().toLowerCase())).size;
  const activity:ActivityRow[]=[
   ...studentsRecent.map(x=>({text:"Student added",detail:`${x.name} → ${x.section.class.department.name} ${x.section.class.semester}`,date:formatDate(x.createdAt),type:"student",timestamp:x.createdAt.getTime()})),
   ...teachersRecent.map(x=>({text:"Teacher added",detail:x.name,date:formatDate(x.createdAt),type:"teacher",timestamp:x.createdAt.getTime()})),
   ...subjectsRecent.map(x=>({text:"Subject added",detail:`${x.name} → ${x.section.class.department.name} ${x.section.class.semester}`,date:formatDate(x.createdAt),type:"subject",timestamp:x.createdAt.getTime()})),
   ...assignmentsRecent.map(x=>({text:"Teacher assigned",detail:`${x.teacher.name} → ${x.subject.name}`,date:formatDate(x.createdAt),type:"assignment",timestamp:x.createdAt.getTime()}))
  ].sort((a,b)=>b.timestamp-a.timestamp).slice(0,6);
  return{props:{adminName:"Admin",counts:{students,teachers,classes:classesCount,subjects:uniqueSubjects},system:{database:true,sheetsLinked:sheetLinks,lastSync:formatDate(latestSync?.lastSyncAt||null)},activity}};
 }catch{return{props:{adminName:"Admin",counts:{students:0,teachers:0,classes:0,subjects:0},system:{database:false,sheetsLinked:0,lastSync:null},activity:[]}}}
};