import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/router";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BarChart3, BookOpen, Download, GraduationCap, LayoutDashboard, RefreshCw, X } from "lucide-react";
import SubjectAnalysisNav from "../../../components/SubjectAnalysisNav";
import { RawDataButton } from "../../../components/AnalysisWidgets";
import { SubjectAnalysis } from "../../../lib/analysis";

type AcademicView = "midsem1" | "midsem2" | "combined" | "summary";
type ExamKey = "midsem1" | "midsem2" | "combined" | "max";
type Tier = "Excellent" | "Good" | "Needs Attention" | "Critical Risk";

const MAX = 30;
const TIERS: Tier[] = ["Excellent", "Good", "Needs Attention", "Critical Risk"];
const COLORS: Record<Tier, string> = { Excellent: "#15966a", Good: "#4d75d0", "Needs Attention": "#f59e0b", "Critical Risk": "#ef4444" };
const round1 = (n: number) => Math.round(n * 10) / 10;
const initials = (name: string) => name.split(" ").filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase();

function median(values: number[]) { if (!values.length) return 0; const sorted = [...values].sort((a,b)=>a-b); const m=Math.floor(sorted.length/2); return sorted.length%2?sorted[m]:round1((sorted[m-1]+sorted[m])/2); }
function valueFor(student:any, exam:ExamKey) { if(exam==="midsem1") return Number(student.midsem?.first||0); if(exam==="midsem2") return Number(student.midsem?.second||0); if(exam==="max") return Number(student.midsem?.max||0); return Number(student.midsem?.combined||0); }
function tierFor(marks:number):Tier { const p=(marks/MAX)*100; if(p>=80)return "Excellent"; if(p>=60)return "Good"; if(p>=40)return "Needs Attention"; return "Critical Risk"; }

export default function SubjectAcademicPage(){
  const router=useRouter(); const {subjectId}=router.query;
  const [view,setView]=useState<AcademicView>("midsem1"); const [data,setData]=useState<SubjectAnalysis|null>(null); const [sheetId,setSheetId]=useState<string|null>(null); const [computedAt,setComputedAt]=useState(""); const [loading,setLoading]=useState(true); const [syncing,setSyncing]=useState(false); const [error,setError]=useState(""); const [selectedTier,setSelectedTier]=useState<Tier|null>(null);
  async function loadAnalysis(sync=false){ if(!subjectId||typeof subjectId!=="string")return; sync?setSyncing(true):setLoading(true); setError(""); try{const r=await fetch(`/api/analysis/subject/${subjectId}${sync?"?sync=1":""}`); const j=await r.json(); if(!r.ok)throw new Error(j.detail?`${j.error}: ${j.detail}`:j.error||"Failed to load academic analysis"); setData(j.data);setComputedAt(j.computedAt||"");setSheetId(j.sheetId||null);}catch(e:any){setError(e.message||"Failed to load academic analysis");}finally{setLoading(false);setSyncing(false);} }
  useEffect(()=>{loadAnalysis();},[subjectId]); useEffect(()=>{setSelectedTier(null);},[view]);
  const students=data?.students||[];
  const statsFor=(exam:"midsem1"|"midsem2")=>{const rows=students.map((s:any)=>({enrollmentNo:s.enrollmentNo,name:s.name,marks:valueFor(s,exam)})); const marks=rows.map(r=>r.marks); const highest=marks.length?Math.max(...marks):0; const counts=TIERS.reduce((r,t)=>({...r,[t]:0}),{} as Record<Tier,number>); rows.forEach(r=>counts[tierFor(r.marks)]++); return {rows,average:marks.length?round1(marks.reduce((a,b)=>a+b,0)/marks.length):0,median:median(marks),highest,highestNames:rows.filter(r=>r.marks===highest).map(r=>r.name),passRate:marks.length?Math.round(rows.filter(r=>r.marks>=12).length/marks.length*100):0,counts,sorted:[...rows].sort((a,b)=>b.marks-a.marks)};};
  const midsem1=useMemo(()=>statsFor("midsem1"),[students]); const midsem2=useMemo(()=>statsFor("midsem2"),[students]);
  const combinedRows=useMemo(()=>students.map((s:any)=>({enrollmentNo:s.enrollmentNo,name:s.name,first:valueFor(s,"midsem1"),second:valueFor(s,"midsem2"),combined:valueFor(s,"combined"),max:valueFor(s,"max")})),[students]);
  const combinedCounts=useMemo(()=>{const r=TIERS.reduce((a,t)=>({...a,[t]:0}),{} as Record<Tier,number>); combinedRows.forEach(row=>r[tierFor(row.combined)]++);return r;},[combinedRows]);
  const activeStats=view==="midsem2"?midsem2:midsem1; const activeLabel=view==="midsem2"?"Midsem 2":"Midsem 1"; const activePie=TIERS.map(name=>({name,value:activeStats.counts[name],color:COLORS[name]})); const displayedRows=selectedTier?activeStats.rows.filter(r=>tierFor(r.marks)===selectedTier):activeStats.rows;
  return <div className="analysis-layout"><aside className="analysis-sidebar"><div className="analysis-brand"><span className="analysis-brand__mark"><BarChart3 size={18}/></span><span>ClassPulse</span></div><nav className="analysis-side-nav"><a href="/dashboard"><LayoutDashboard size={18}/>Dashboard</a><a href="/classes"><BookOpen size={18}/>Class Analysis</a><a className="is-active" href={typeof subjectId==="string"?`/subject-analysis/${subjectId}/academic`:"#"}><GraduationCap size={18}/>Subject Analysis</a></nav><RawDataButton sheetId={sheetId}/><div className="analysis-side-footer">ClassPulse Teacher Portal</div></aside><main className="analysis-page"><header className="analysis-topbar"><div className="analysis-title-row"><h1>Subject Analysis</h1>{computedAt&&<span className="analysis-sync">• Last synced {new Date(computedAt).toLocaleString()}</span>}</div><div className="analysis-top-actions"><button className="analysis-primary" onClick={()=>loadAnalysis(true)} disabled={syncing}><RefreshCw size={15} className={syncing?"animate-spin":""}/>{syncing?"Syncing...":"Sync now"}</button></div></header>
  {typeof subjectId==="string"&&<SubjectAnalysisNav subjectId={subjectId}/>}<div className="analysis-view-switch">{([["midsem1","Midsem 1"],["midsem2","Midsem 2"],["combined","Combined"],["summary","Summary"]] as [AcademicView,string][]).map(([k,l])=><button key={k} className={view===k?"is-active":""} onClick={()=>setView(k)}>{l}</button>)}</div>
  {error&&<div className="analysis-panel" style={{padding:14,marginBottom:16,color:"#b42318"}}>{error}</div>}{loading&&!data&&<div style={{padding:40,color:"#667085",fontSize:13}}>Loading academic analysis...</div>}
  {data&&(view==="midsem1"||view==="midsem2")&&<><section className="analysis-hero"><div className="analysis-hero-copy"><h2>{activeLabel}</h2><p>Raw Midsem marks out of 30, class statistics, and performance tiers.</p></div><Metric label="Class Average" value={activeStats.average} detail="out of 30 marks"/><Metric label="Class Median" value={activeStats.median} detail="middle class score"/><Metric label="Pass Rate" value={`${activeStats.passRate}%`} detail="students scoring 12 or more"/></section>
  <section className="analysis-content-grid academic-content-grid"><section className="analysis-panel analysis-table-panel"><div className="analysis-panel-head"><div><h3>Data Sheet</h3><p style={{marginTop:4,color:"#98a2b3",fontSize:11}}>Pass mark: 12/30 (40%){selectedTier?` · Filtered: ${selectedTier}`:""}</p></div><div style={{display:"flex",alignItems:"center",gap:8}}>{selectedTier&&<button className="analysis-secondary" style={{padding:"5px 8px"}} onClick={()=>setSelectedTier(null)}><X size={13}/>Clear</button>}<span className="analysis-count">{displayedRows.length} Students</span></div></div><div className="analysis-table-wrap academic-table-wrap"><table className="analysis-table"><thead><tr><th>Student</th><th>Marks</th><th>Percentage</th><th>Status</th></tr></thead><tbody>{displayedRows.map(row=>{const pass=row.marks>=12,p=Math.round(row.marks/MAX*100);return <tr key={row.enrollmentNo}><td><span className="student-cell"><span className="student-avatar">{initials(row.name)}</span>{row.name}</span></td><td className={pass?"change-up":"change-down"}>{row.marks}</td><td>{p}%</td><td><span className={`trend-badge ${pass?"trend-up":"trend-down"}`}>{pass?"Pass":"Fail"}</span></td></tr>;})}{!displayedRows.length&&<tr><td colSpan={4} style={{textAlign:"center",padding:32,color:"#667085"}}>No students in this performance tier.</td></tr>}</tbody></table></div></section>
  <div className="analysis-right-stack"><section className="analysis-panel academic-stats-panel"><div className="academic-highest"><span>Highest Score</span><strong>{activeStats.highest}</strong><p>{activeStats.highestNames.join(", ")||"—"}</p></div><div className="academic-tier-grid">{TIERS.map(t=><button key={t} type="button" className="academic-tier-card" onClick={()=>setSelectedTier(selectedTier===t?null:t)} style={{borderColor:`${COLORS[t]}55`,cursor:"pointer",boxShadow:selectedTier===t?`0 0 0 2px ${COLORS[t]}33`:undefined}}><span>{t}</span><strong style={{color:COLORS[t]}}>{activeStats.counts[t]}</strong></button>)}</div></section><section className="analysis-panel analysis-chart-panel"><h3>Performance Tier</h3><p>Click a chart segment to filter the student table.</p><div className="analysis-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={activePie} dataKey="value" nameKey="name" innerRadius={54} outerRadius={82} paddingAngle={3} onClick={(entry:any)=>{const t=entry?.name as Tier|undefined;if(t&&TIERS.includes(t))setSelectedTier(selectedTier===t?null:t);}}>{activePie.map(e=><Cell key={e.name} fill={e.color} cursor="pointer" opacity={!selectedTier||selectedTier===e.name?1:.35}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></section><div className="academic-rank-grid"><section className="analysis-panel academic-rank-panel"><h3>Top 5 Highest Scorers</h3>{activeStats.sorted.slice(0,5).map((r,i)=><div className="academic-rank-row" key={r.enrollmentNo}><span>{i+1}</span><p>{r.name}</p><strong>{r.marks}</strong></div>)}</section><section className="analysis-panel academic-rank-panel"><h3>Bottom 5 At-Risk Students</h3>{[...activeStats.sorted].reverse().slice(0,5).map((r,i)=><div className="academic-rank-row" key={r.enrollmentNo}><span>{i+1}</span><p>{r.name}</p><strong className="is-negative">{r.marks}</strong></div>)}</section></div></div></section></>}
  {data&&view==="combined"&&<><section className="analysis-hero"><div className="analysis-hero-copy"><h2>Midsem Combined</h2><p>Compare both Midsem examinations in one view.</p></div><Metric label="Students" value={combinedRows.length} detail="combined records"/><Metric label="Class Average" value={combinedRows.length?round1(combinedRows.reduce((s,r)=>s+r.combined,0)/combinedRows.length):0} detail="combined average"/><Metric label="Best Score" value={combinedRows.length?Math.max(...combinedRows.map(r=>r.max)):0} detail="best individual result"/></section><section className="analysis-panel analysis-table-panel"><div className="analysis-panel-head"><h3>All Students</h3><span className="analysis-count">{combinedRows.length} Students</span></div><div className="analysis-table-wrap academic-table-wrap"><table className="analysis-table"><thead><tr><th>Student</th><th>Midsem 1</th><th>Midsem 2</th><th>Combined</th><th>Max</th></tr></thead><tbody>{combinedRows.map(r=><tr key={r.enrollmentNo}><td className="student-cell">{r.name}</td><td>{r.first}</td><td>{r.second}</td><td>{r.combined}</td><td>{r.max}</td></tr>)}</tbody></table></div></section></>}
  {data&&view==="summary"&&<section className="analysis-content-grid"><section className="analysis-panel analysis-table-panel"><div className="analysis-panel-head"><h3>Academic Summary</h3><span className="analysis-count">{students.length} Students</span></div><div className="analysis-table-wrap academic-table-wrap"><table className="analysis-table"><thead><tr><th>Student</th><th>Midsem 1</th><th>Midsem 2</th><th>Change</th></tr></thead><tbody>{combinedRows.map(r=>{const c=round1(r.second-r.first);return <tr key={r.enrollmentNo}><td className="student-cell">{r.name}</td><td>{r.first}</td><td>{r.second}</td><td className={c>=0?"change-up":"change-down"}>{c>0?"+":""}{c}</td></tr>;})}</tbody></table></div></section><section className="analysis-panel analysis-chart-panel"><h3>Combined Grade Distribution</h3><p>Students grouped by their combined Midsem performance.</p><div className="analysis-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={TIERS.map(t=>({name:t,count:combinedCounts[t]}))}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" fontSize={10}/><YAxis allowDecimals={false} fontSize={11}/><Tooltip/><Bar dataKey="count" radius={[6,6,0,0]}>{TIERS.map(t=><Cell key={t} fill={COLORS[t]}/>)}</Bar></BarChart></ResponsiveContainer></div></section></section>}
  </main></div>;
}
function Metric({label,value,detail}:{label:string;value:string|number;detail:string}){return <div className="analysis-metric"><div className="analysis-metric-content"><span className="analysis-metric-label">{label}</span><div className="analysis-metric-value-row"><strong>{value}</strong></div><span className="analysis-metric-detail">{detail}</span></div></div>;}
