import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/router";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Cell } from "recharts";
import { BarChart3, BookOpen, Download, Gauge, GraduationCap, LayoutDashboard, Mail, RefreshCw, Search, SlidersHorizontal, Sparkles, Users, AlertCircle } from "lucide-react";
import SubjectAnalysisNav from "../../../components/SubjectAnalysisNav";
import { SubjectAnalysis } from "../../../lib/analysis";
import { RawDataButton } from "../../../components/AnalysisWidgets";

type AttendanceView = "trend" | "risk";
const initials = (name: string) => name.split(" ").filter(Boolean).slice(0, 2).map((x) => x[0]).join("").toUpperCase();
const round1 = (n: number) => Math.round(n * 10) / 10;

export default function SubjectAttendancePage() {
  const router = useRouter(); const { subjectId } = router.query;
  const [view, setView] = useState<AttendanceView>("trend"); const [data, setData] = useState<SubjectAnalysis | null>(null);
  const [sheetId, setSheetId] = useState<string | null>(null); const [computedAt, setComputedAt] = useState("");
  const [loading, setLoading] = useState(true); const [syncing, setSyncing] = useState(false); const [error, setError] = useState("");
  const [previousMonth, setPreviousMonth] = useState(""); const [currentMonth, setCurrentMonth] = useState(""); const [trendCriteria, setTrendCriteria] = useState(5);
  const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [lowerBound, setLowerBound] = useState(0); const [upperBound, setUpperBound] = useState(100);
  const [riskTrendFilter, setRiskTrendFilter] = useState("All"); const [riskMonth, setRiskMonth] = useState<"previous" | "current">("current"); const [copied, setCopied] = useState(false);

  async function loadAnalysis(sync=false, previous=previousMonth, current=currentMonth, criteria=trendCriteria) {
    if (!subjectId || typeof subjectId !== "string") return; sync ? setSyncing(true) : setLoading(true); setError("");
    try { const params = new URLSearchParams(); if(sync) params.set("sync","1"); if(previous) params.set("previousMonth",previous); if(current) params.set("currentMonth",current); params.set("trendCriteria",String(criteria));
      const res = await fetch(`/api/analysis/subject/${subjectId}?${params.toString()}`); const json = await res.json(); if(!res.ok) throw new Error(json.detail ? `${json.error}: ${json.detail}` : json.error || "Failed to load attendance analysis");
      setData(json.data); setComputedAt(json.computedAt||""); setSheetId(json.sheetId||null); setPreviousMonth(previous||json.data?.monthsUsed?.previous||""); setCurrentMonth(current||json.data?.monthsUsed?.current||""); setPage(1);
    } catch(e:any){setError(e.message||"Failed to load attendance analysis");} finally {setLoading(false);setSyncing(false);}
  }
  useEffect(()=>{loadAnalysis();},[subjectId]);

  const students:any[] = data?.students || []; const availableMonths = data?.availableMonths || [];
  const filteredStudents = useMemo(()=>students.filter((s:any)=>s.name.toLowerCase().includes(search.toLowerCase())),[students,search]);
  const perPage=10, pageCount=Math.max(1,Math.ceil(filteredStudents.length/perPage)), visibleStudents=filteredStudents.slice((page-1)*perPage,page*perPage);
  const previousAverage=students.length?round1(students.reduce((a:number,s:any)=>a+(s.attendancePct?.prevMonth||0),0)/students.length):0;
  const currentAverage=students.length?round1(students.reduce((a:number,s:any)=>a+(s.attendancePct?.currMonth||0),0)/students.length):0;
  const averageChange=round1(currentAverage-previousAverage), improvingCount=students.filter((s:any)=>s.attendancePct?.trend==="Increasing").length;
  const trendData=[{name:"Increasing",count:data?.trendCounts?.increasing||0,color:"#16a56a"},{name:"Decreasing",count:data?.trendCounts?.decreasing||0,color:"#ef4444"},{name:"Stable",count:data?.trendCounts?.stable||0,color:"#4d75d0"}];
  const attendanceDistribution=[{name:"Below 30%",count:data?.attendanceBuckets?.below30||0,color:"#ef4444"},{name:"30% to 49%",count:data?.attendanceBuckets?.to49||0,color:"#f97316"},{name:"50% to 74%",count:data?.attendanceBuckets?.to74||0,color:"#f59e0b"},{name:"75% and above",count:data?.attendanceBuckets?.above75||0,color:"#15966a"}];
  const riskResults=useMemo(()=>students.filter((s:any)=>{const pct=riskMonth==="current"?s.attendancePct?.currMonth??0:s.attendancePct?.prevMonth??0; return pct>=lowerBound&&pct<=upperBound&&(riskTrendFilter==="All"||s.attendancePct?.trend===riskTrendFilter);}),[students,lowerBound,upperBound,riskTrendFilter,riskMonth]);
  const riskEmails=riskResults.map((s:any)=>s.email).filter(Boolean);
  function openRisk(o:{trend?:string;lower?:number;upper?:number}){setRiskTrendFilter(o.trend||"All");setLowerBound(o.lower??0);setUpperBound(o.upper??100);setView("risk");}
  async function copyEmails(){try{await navigator.clipboard.writeText(riskEmails.join("; "));setCopied(true);setTimeout(()=>setCopied(false),1800);}catch{}}

  return <div className="analysis-layout">
    <aside className="analysis-sidebar"><div className="analysis-brand"><span className="analysis-brand__mark"><BarChart3 size={18}/></span><span>ClassPulse</span></div><nav className="analysis-side-nav"><a href="/dashboard"><LayoutDashboard size={18}/>Dashboard</a><a href="/classes"><BookOpen size={18}/>Class Analysis</a><a className="is-active" href={typeof subjectId==="string"?`/subject-analysis/${subjectId}/attendance`:"#"}><GraduationCap size={18}/>Subject Analysis</a></nav><div className="analysis-side-footer">ClassPulse Teacher Portal</div></aside>
    <main className="analysis-page"><header className="analysis-topbar"><div className="analysis-title-row"><h1>Subject Analysis</h1>{computedAt&&<span className="analysis-sync">• Last synced {new Date(computedAt).toLocaleString()}</span>}</div><div className="analysis-top-actions"><RawDataButton sheetId={sheetId}/><button className="analysis-primary" onClick={()=>loadAnalysis(true)} disabled={syncing}><RefreshCw size={15} className={syncing?"animate-spin":""}/>{syncing?"Syncing...":"Sync now"}</button></div></header>
      {typeof subjectId==="string"&&<SubjectAnalysisNav subjectId={subjectId}/>}<div className="analysis-view-switch"><button className={view==="trend"?"is-active":""} onClick={()=>setView("trend")}>Trend</button><button className={view==="risk"?"is-active":""} onClick={()=>setView("risk")}>At Risk</button></div>
      {error&&<div className="analysis-panel" style={{padding:14,marginBottom:16,color:"#b42318",display:"flex",gap:8}}><AlertCircle size={17}/>{error}</div>}{loading&&!data&&<div style={{padding:40,color:"#667085",fontSize:13}}>Loading attendance analysis...</div>}
      {data&&view==="trend"&&<><section className="analysis-hero"><div className="analysis-hero-copy"><h2>Attendance Trend</h2><p>Compare attendance between two months and identify increasing, decreasing, and stable students.</p></div><Metric icon={<Users size={19}/>} label={`Class Average (${previousMonth||"Previous"})`} value={`${previousAverage}%`} change={averageChange}/><Metric icon={<Gauge size={19}/>} label={`Class Average (${currentMonth||"Current"})`} value={`${currentAverage}%`} change={averageChange}/><Metric icon={<Sparkles size={19}/>} label="Students Improving" value={improvingCount} detail={`${students.length?round1(improvingCount/students.length*100):0}% of total students`} good/></section>
        <section className="analysis-panel analysis-settings"><h3>Trend Comparison Settings</h3><div className="analysis-settings-grid"><div><label>First Month</label><select value={previousMonth} onChange={e=>setPreviousMonth(e.target.value)}>{availableMonths.map((m:string)=><option key={m}>{m}</option>)}</select></div><div><label>Second Month</label><select value={currentMonth} onChange={e=>setCurrentMonth(e.target.value)}>{availableMonths.map((m:string)=><option key={m}>{m}</option>)}</select></div><div><label>Trend Criteria (%)</label><input type="number" min="0" max="100" value={trendCriteria} onChange={e=>setTrendCriteria(Number(e.target.value))}/></div><button className="analysis-primary" onClick={()=>loadAnalysis(false,previousMonth,currentMonth,trendCriteria)} disabled={loading||!previousMonth||!currentMonth||previousMonth===currentMonth}><SlidersHorizontal size={15}/>{loading?"Applying...":"Apply Comparison"}</button></div><div className="analysis-note"><AlertCircle size={14}/>Trend calculation: a change of <strong>±{trendCriteria} percentage points</strong> or more is Increasing or Decreasing.</div></section>
        <section className="analysis-content-grid"><div className="analysis-panel analysis-table-panel"><div className="analysis-panel-head"><div style={{display:"flex",alignItems:"center",gap:8}}><h3>Student Trend Analysis</h3><span className="analysis-count">{students.length} Students</span></div><div style={{position:"relative"}}><Search size={15} style={{position:"absolute",left:10,top:11,color:"#98a2b3"}}/><input placeholder="Search student..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} style={{paddingLeft:32,width:200,height:38}}/></div></div><div className="analysis-table-wrap"><table className="analysis-table"><thead><tr><th>Student Name</th><th>{data.monthsUsed?.previous||"Month 1"}</th><th>{data.monthsUsed?.current||"Month 2"}</th><th>Change</th><th>Trend</th></tr></thead><tbody>{visibleStudents.map((s:any)=>{const prev=s.attendancePct?.prevMonth??0,curr=s.attendancePct?.currMonth??0,change=round1(curr-prev),trend=s.attendancePct?.trend||"Stable";return <tr key={s.enrollmentNo}><td><span className="student-cell"><span className="student-avatar">{initials(s.name)}</span>{s.name}</span></td><td>{prev}%</td><td>{curr}%</td><td className={change>0?"change-up":change<0?"change-down":""}>{change>0?"+":""}{change}%</td><td><span className={`trend-badge ${trend==="Increasing"?"trend-up":trend==="Decreasing"?"trend-down":"trend-stable"}`}>{trend==="Increasing"?"↑ ":trend==="Decreasing"?"↓ ":"− "}{trend}</span></td></tr>})}</tbody></table></div><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginTop:14,color:"#667085",fontSize:11}}><span>Showing {filteredStudents.length?(page-1)*perPage+1:0} to {Math.min(page*perPage,filteredStudents.length)} of {filteredStudents.length} students</span><div style={{display:"flex",gap:6}}>{Array.from({length:Math.min(pageCount,5)},(_,i)=>i+1).map(n=><button key={n} onClick={()=>setPage(n)} style={{width:30,height:30,borderRadius:7,border:n===page?"0":"1px solid #e2e8f0",background:n===page?"#2f246f":"transparent",color:n===page?"white":"#667085",fontSize:11}}>{n}</button>)}</div></div></div><div className="analysis-right-stack"><ChartPanel title="Trend Distribution" subtitle="Click a column to filter those students in At Risk." data={trendData} onBarClick={(e:any)=>openRisk({trend:e?.name||"All"})}/><ChartPanel title="Attendance Distribution" subtitle="Click a column to open that attendance range in At Risk." data={attendanceDistribution} onBarClick={(e:any)=>{const n=e?.name;if(n==="Below 30%")openRisk({lower:0,upper:29.999});else if(n==="30% to 49%")openRisk({lower:30,upper:49.999});else if(n==="50% to 74%")openRisk({lower:50,upper:74.999});else openRisk({lower:75,upper:100});}}/></div></section>
        <section className="analysis-panel analysis-insight"><Sparkles size={23} color="#4f46e5"/><div className="analysis-insight-copy"><h4>Insight</h4><p>Attendance {averageChange<0?`declined by ${Math.abs(averageChange)}%`:averageChange>0?`improved by ${averageChange}%`:"remained stable"} from {previousMonth} to {currentMonth}. Focus on students with decreasing trends and low attendance.</p></div><div className="analysis-insight-actions"><button className="analysis-secondary" onClick={()=>openRisk({lower:0,upper:49.999})}><Mail size={15}/>Copy to Mail</button><a className="analysis-primary" href={`mailto:?bcc=${encodeURIComponent(students.filter((s:any)=>s.attendancePct?.currMonth<50).map((s:any)=>s.email).filter(Boolean).join(","))}`}><Mail size={15}/>Send Alert Emails</a></div></section></>}
      {data&&view==="risk"&&<><section className="analysis-hero"><div className="analysis-hero-copy"><h2>At Risk Students</h2><p>Filter students by attendance range and trend, then copy or email the selected list.</p></div></section><section className="analysis-panel analysis-settings"><h3>Filter Criteria</h3><div className="analysis-settings-grid"><div><label>Lower Bound (%)</label><input type="number" value={lowerBound} onChange={e=>setLowerBound(Number(e.target.value))}/></div><div><label>Upper Bound (%)</label><input type="number" value={upperBound} onChange={e=>setUpperBound(Number(e.target.value))}/></div><div><label>Trend</label><select value={riskTrendFilter} onChange={e=>setRiskTrendFilter(e.target.value)}><option>All</option><option>Increasing</option><option>Decreasing</option><option>Stable</option></select></div><div><label>Month</label><select value={riskMonth} onChange={e=>setRiskMonth(e.target.value as "previous"|"current")}><option value="current">{currentMonth}</option><option value="previous">{previousMonth}</option></select></div></div></section><section className="analysis-panel analysis-table-panel"><div className="analysis-panel-head"><h3>Filtered Students</h3><span className="analysis-count">{riskResults.length} Students</span></div><div className="analysis-table-wrap"><table className="analysis-table"><thead><tr><th>Name</th><th>Enrollment</th><th>Attendance</th><th>Trend</th><th>Email</th></tr></thead><tbody>{riskResults.map((s:any)=>{const pct=riskMonth==="current"?s.attendancePct?.currMonth:s.attendancePct?.prevMonth;return <tr key={s.enrollmentNo}><td>{s.name}</td><td>{s.enrollmentNo}</td><td>{pct}%</td><td>{s.attendancePct?.trend||"Stable"}</td><td>{s.email||"—"}</td></tr>})}</tbody></table></div><div className="analysis-insight-actions" style={{marginTop:16,justifyContent:"flex-end"}}><button className="analysis-secondary" onClick={copyEmails}><Download size={15}/>{copied?"Copied":"Copy Emails"}</button><a className="analysis-primary" href={`mailto:?bcc=${encodeURIComponent(riskEmails.join(","))}`}><Mail size={15}/>Send Alert Emails</a></div></section></>}
    </main></div>;
}

function Metric({icon,label,value,change,detail,good}:{icon:React.ReactNode;label:string;value:string|number;change?:number;detail?:string;good?:boolean}){return <div className="analysis-metric"><div className="analysis-metric-top"><span className="analysis-metric-icon">{icon}</span><span>{label}</span></div><div className="analysis-metric-value"><strong>{value}</strong>{detail?<span className={good?"good":""}>{detail}</span>:change!==undefined&&<span className={change>=0?"good":""}>{change>0?"↑ +":change<0?"↓ ":""}{change}%</span>}</div></div>}
function ChartPanel({title,subtitle,data,onBarClick}:{title:string;subtitle:string;data:{name:string;count:number;color:string}[];onBarClick:(entry:any)=>void}){return <section className="analysis-panel analysis-chart-panel"><div className="analysis-panel-head"><div><h3>{title}</h3><p>{subtitle}</p></div></div><div className="analysis-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{top:18,right:8,left:-18,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" fontSize={10}/><YAxis allowDecimals={false} fontSize={10}/><Tooltip cursor={{fill:"rgba(79,70,229,.04)"}} formatter={(v:any)=>[v,"Students"]}/><Bar dataKey="count" radius={[4,4,0,0]} cursor="pointer" onClick={onBarClick}>{data.map(e=><Cell key={e.name} fill={e.color}/>)}</Bar></BarChart></ResponsiveContainer></div></section>}
