'use client';
import { useState } from 'react'; import * as XLSX from 'xlsx'; import { createClient } from '@/lib/supabase';
type ClassItem={id:string;branch:string;batch:string;section:string}; type Row={ 'Enrollment Number':string; 'Student Name':string };
const columns=['Enrollment Number','Student Name'];
export function StudentRosterUpload({classes}:{classes:ClassItem[]}) { const [classId,setClassId]=useState(''); const [rows,setRows]=useState<Row[]>([]); const [errors,setErrors]=useState<string[]>([]); const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false);
  function download(){const sheet=XLSX.utils.json_to_sheet([{'Enrollment Number':'BT2023ECE001','Student Name':'Student name'}]);const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'Students');XLSX.writeFile(book,'classpulse-student-roster-template.xlsx')}
  async function choose(file?:File){if(!file)return;setMessage('');const data=await file.arrayBuffer();const book=XLSX.read(data,{type:'array'});const sheet=book.Sheets[book.SheetNames[0]];const parsed=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:''});const found=Object.keys(parsed[0]??{});const issues=columns.filter(c=>!found.includes(c)).map(c=>`Missing required column: ${c}`);const seen=new Set<string>();const valid:Row[]=[];parsed.forEach((item,index)=>{const enrollment=String(item['Enrollment Number']??'').trim(),name=String(item['Student Name']??'').trim();if(!enrollment||!name)issues.push(`Row ${index+2}: enrollment number and student name are required.`);else if(seen.has(enrollment))issues.push(`Row ${index+2}: duplicate enrollment number ${enrollment}.`);else{seen.add(enrollment);valid.push({'Enrollment Number':enrollment,'Student Name':name})}});if(classId&&valid.length){const{data}=await createClient().from('students').select('enrollment_number').eq('class_id',classId);const existing=new Set((data??[]).map(x=>x.enrollment_number));valid.forEach((r,index)=>{if(existing.has(r['Enrollment Number']))issues.push(`Row ${index+2}: ${r['Enrollment Number']} is already in this class.`)})}setRows(valid);setErrors(issues)}
  async function save(){if(!classId||!rows.length||errors.length)return;setSaving(true);const {error}=await createClient().from('students').insert(rows.map(r=>({class_id:classId,enrollment_number:r['Enrollment Number'],full_name:r['Student Name']})));setSaving(false);setMessage(error?.message??`${rows.length} students saved. Refresh the page to see them.`);if(!error){setRows([])}}
  return <div className="rounded-lg border bg-slate-50 p-4"><h3 className="font-semibold">Upload student roster from Excel</h3><p className="mt-1 text-sm text-slate-600">Use the supplied two-column template. The Excel file stays in your browser; only checked student records are saved.</p><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="label">Student group<select value={classId} onChange={e=>{setClassId(e.target.value);setRows([]);setErrors([])}} required><option value="">Choose student group</option>{classes.map(c=><option value={c.id} key={c.id}>{c.branch} · {c.batch} · Section {c.section}</option>)}</select></label><div className="flex items-end"><button type="button" onClick={download} className="btn-secondary">Download Excel template</button></div></div><label className="label mt-3">Completed roster file<input type="file" accept=".xlsx,.xls" disabled={!classId} onChange={e=>void choose(e.target.files?.[0])}/></label>{rows.length>0&&<p className="mt-2 text-sm">Ready to import: <b>{rows.length}</b> students.</p>}{errors.length>0&&<ul className="mt-3 max-h-32 overflow-auto rounded bg-red-50 p-3 text-sm text-red-700">{errors.map((error,index)=><li key={index}>{error}</li>)}</ul>}{message&&<p className="mt-3 rounded bg-sky-50 p-3 text-sm text-blue-800">{message}</p>}<button type="button" disabled={!classId||!rows.length||!!errors.length||saving} onClick={()=>void save()} className="btn mt-3">{saving?'Saving…':'Save roster'}</button></div> }
